import "./globals.css";
import type { ReactNode } from "react";
import { type Metadata } from "next";
import { getBaseUrl } from "@/utils/get-base-url";
import RootProvider from "@/components/root-provider";
import Menu from "./menu";
import { fetchUser } from "@/server/logto/fetch-user";

export const metadata = {
  title: "Next App",
  description: "Generated by @chiastack/nextjs-app template",
  metadataBase: new URL(
    getBaseUrl({
      isServer: true,
    })
  ),
} satisfies Metadata;

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const user = await fetchUser();
  return (
    <html lang="en">
      <body className="transition-all duration-700 ease-in-out">
        <RootProvider>
          <Menu
            status={user.isAuthenticated ? "authenticated" : "unauthenticated"}
          />
          {children}
        </RootProvider>
      </body>
    </html>
  );
}
