import "./globals.css";
import type { ReactNode } from "react";
import { type Metadata } from "next";
import { getBaseUrl } from "@/utils/get-base-url";

export const metadata = {
  title: "Next App",
  description: "Generated by @chiastack/nextjs-app template",
  metadataBase: new URL(
    getBaseUrl({
      isServer: true,
    })
  ),
} satisfies Metadata;

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
